"""create-documents

Revision ID: 7a2fc2819734
Revises: 0cb7c0c0a184
Create Date: 2025-01-29 02:17:03.681264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2fc2819734'
down_revision = '0cb7c0c0a184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('company_to', sa.String(length=255), nullable=True),
    sa.Column('company_from', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_text', sa.Text(), nullable=True),
    sa.Column('is_elastic_migrated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
